# Settings file - Auto-generated by GUI
dataCollectionMode = False
showBoundingBox = True

### AIM ASSIST SETTINGS ###
aimAssist = True
speedX = 70
speedY = 70
aimSmoothing = False
boundingBoxWidth = 561
boundingBoxHeight = 389
boundingBoxColor = [102, 51, 153]
adaptiveBoundingBox = False
manualOveride = False
manualOverridePercentage = 50

# NEW: Smooth Aim Control
smoothAimFactor = 0.00

# Color detection settings
target_color_lower = [100, 150, 150]
target_color_upper = [140, 255, 255]

# YOLO Settings
useYOLO = False  # Set to True to enable YOLO detection
yoloConfidence = 0.5  # Confidence threshold (0.0-1.0)
targetClasses = [0]  # COCO class IDs: 0=person, 1=bicycle, 2=car, etc.

# Activation Button
aimActivationButton = "BUTTON_7"

# Aim Offset
aimOffsetX = 0
aimOffsetY = 41
colorConfidence = 0.85
detectionLatency = 5

# NEW: Prediction settings for moving targets
predictionStrength = 70

# Noise Reduction Settings
minPixelArea = 12        # Minimum pixel area to consider as valid target
maxPixelArea = 200      # Maximum pixel area to avoid large false positives
aspectRatioMin = 0.3    # Minimum width/height ratio
aspectRatioMax = 3.0    # Maximum width/height ratio  
densityThreshold = 0.37  # Minimum pixel density (area/(w*h)) to avoid sparse noiseaimActivationButton = "L2"
