# Settings file - Auto-generated by GUI
# F4Vision HARD LOCK Configuration

### BASIC SETTINGS ###
dataCollectionMode = False
showBoundingBox = True
adaptiveBoundingBox = False

### HARD LOCK AIM SETTINGS ###
aimAssist = True
speedX = 53
speedY = 53
aimSmoothing = False  # FORCE DISABLED for hard lock
smoothAimFactor = 0.0  # FORCE ZERO for hard lock

### DETECTION BOX SETTINGS ###
boundingBoxWidth = 771
boundingBoxHeight = 523
boundingBoxColor = [102, 51, 153]

### MANUAL OVERRIDE SETTINGS ###
manualOveride = False
manualOverridePercentage = 50

### COLOR DETECTION SETTINGS ###
colorConfidence = 0.80
target_color_lower = [100, 150, 150]
target_color_upper = [140, 255, 255]

### NOISE REDUCTION SETTINGS ###
minPixelArea = 12
maxPixelArea = 200
aspectRatioMin = 0.3
aspectRatioMax = 3.0
densityThreshold = 0.37

### ACTIVATION BUTTON ###
aimActivationButton = "BUTTON_7"

### AIM OFFSET ###
aimOffsetX = 0
aimOffsetY = 46

### DETECTION LATENCY ###
detectionLatency = 5

### PREDICTION SETTINGS ###
predictionStrength = 70
movementPrediction = True

### HARD LOCK BEHAVIOR ###
lockStrength = 80
stickyAim = True

### ADVANCED FEATURES ###
rotationalAA = True
microCorrections = True
headshotPriority = True